# Generated by Django 4.0.4 on 2022-05-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteshare',
            unique_together={('note', 'user')},
        ),
    ]
